# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17UHYwlZAehvNPmDkO9wr1T9s-p-zFkYG
"""

!pip install colabcode

!pip install fastapi nest-asyncio pyngrok uvicorn

!pip install pydantic

!pip install jinja2

!pip install fastapi

import fastapi
from fastapi import FastAPI
import nest_asyncio
from pyngrok import ngrok
import uvicorn
import jinja2
import pydantic
from pydantic import BaseModel
from fastapi.templating import Jinja2Templates
from typing import Optional
import colabcode
from colabcode import ColabCode

cc=ColabCode(port=5000,code=False)

cc

app=FastAPI()

@app.get('/')
async def read_root():
  return {'hello':'world'}

cc.run_app(app=app)